echo "#"
echo "# Config file for sSMTP sendmail"
echo "#"
echo "# The person who gets all mail for userids < 1000"
echo "# Make this empty to disable rewriting."
echo "root=postmaster"
echo ""
echo "# The place where the mail goes. The actual machine name is required no "
echo "# MX records are consulted. Commonly mailhosts are named mail.domain.com"
echo "mailhub=smtp.gmail.com:587"
echo ""
echo "# Where will the mail seem to come from?"
echo "#rewriteDomain="
echo "AuthUser=majorminor658@gmail.com"
echo "AuthPass=majorminor123"
echo "UseSTARTTLS=YES"
echo "TLS_CA_File=/etc/pki/tls/certs/ca-bundle.crt"
echo ""
echo "# The full hostname"
echo "hostname=$HOSTNAME"
echo ""
echo "# Are users allowed to set their own From: address?"
echo "# YES - Allow the user to specify their own From: address"
echo "# NO - Use the system generated From: address"
echo "#FromLineOverride=YES"
echo ""